apiVersion: v1alpha1
kind: Role
metadata:
  name: halo-weread-plugin-role-anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "微信读书插件"
    rbac.authorization.halo.run/display-name: "公开书架资源访问"
rules:
  - nonResourceURLs:
      - /halo-weread-plugin/books
      - /halo-weread-plugin/books/*/notes
      - /halo-weread-plugin/shelf-html
    verbs:
      - get
  - apiGroups:
      - run.halo.plugin.wereadplugin
    resources:
      - wereadbooks
    verbs:
      - get
      - list
